name: Uploader
on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: composer install --no-dev -o
      # Make a ZIP
      - name: Upload binaries to release
        uses: papeloto/action-zip@v1
        with:
          files: src/ actions-test.php
          recursive: true
          dest: actions-test.zip

      - name: Upload ZIP to release
      - uses: actions/upload-artifact@v1
        with:
          name: actions-test.zip
          path: ${{ github.workspace }}/actions-test.zip.zip
