name: Uploader

on:
  push:
    tags:
      - "*"
  release:
    types: [published]

jobs:
  zip:
    name: ZIP
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create ZIP
        uses: papeloto/action-zip@v1
        with:
          files: src/ actions-test.php
          recursive: false
          dest: actions-test-${{ github.ref }}.zip

      - name: Upload ZIP to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: actions-test-${{ github.ref }}.zip
          tag: ${{ github.ref }}
