name: Uploader
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: composer install --no-dev -o
      # Make a ZIP
      - name: Upload binaries to release
        uses: papeloto/action-zip@v1
        with:
          files: src/ actions-test.php
          recursive: true
          dest: actions-test.zip
      - name: Upload ZIP to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: actions-test.zip
          asset_name: actions-test-${{ github.ref }}.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "Release was generated at commit ${{github.sha}}"
      
