name: Uploader
on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Install
      - name: composer
        run: composer install --no-dev -o
      # Make a ZIP
      - name: Upload binaries to release
      - uses: papeloto/action-zip@v1
        with:
          files: vendor/ src/ actions-test.php
          recursive: true
          dest: actions-test.zip
        # Upload to release
      - name: Upload ZIP to release
      - uses: actions/upload-artifact@v1
        with:
          name: actions-test.zip
          path: ${{ github.workspace }}/actions-test.zip
