name: Uploader

on:
  push:
    tags:
      - "*"

jobs:
  
  zip2:
    name: ZIP2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'r-2.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig tests/* bin/*'
