name: Uploader

on:
  push:
    tags:
      - "*"

jobs:
  zip:
    name: ZIP
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #
      - name: Upload binaries to release
        uses: papeloto/action-zip@v1
        with:
          files: src/ actions-test.php
          recursive: true
          dest: actions-test.zip
      
